// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC48jjWR1wWhJlh7aX-dbP3824_XJ2YerU',
    appId: '1:540769076114:web:9a937d8ba6f48f3199b74b',
    messagingSenderId: '540769076114',
    projectId: 'nas-box',
    authDomain: 'nas-box.firebaseapp.com',
    storageBucket: 'nas-box.appspot.com',
    measurementId: 'G-3010F2PH65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Zhag93nPAjMtpqYfWb_OcoMxy6nxQFU',
    appId: '1:540769076114:android:005748d4dc29a63e99b74b',
    messagingSenderId: '540769076114',
    projectId: 'nas-box',
    storageBucket: 'nas-box.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMcn7HfwA1Uo0iunLCtT-Vm9nPCIkl8gQ',
    appId: '1:540769076114:ios:fc02c86c4c956dc999b74b',
    messagingSenderId: '540769076114',
    projectId: 'nas-box',
    storageBucket: 'nas-box.appspot.com',
    iosBundleId: 'com.example.naskrypt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMcn7HfwA1Uo0iunLCtT-Vm9nPCIkl8gQ',
    appId: '1:540769076114:ios:fc02c86c4c956dc999b74b',
    messagingSenderId: '540769076114',
    projectId: 'nas-box',
    storageBucket: 'nas-box.appspot.com',
    iosBundleId: 'com.example.naskrypt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC48jjWR1wWhJlh7aX-dbP3824_XJ2YerU',
    appId: '1:540769076114:web:54c65a1973cecd3799b74b',
    messagingSenderId: '540769076114',
    projectId: 'nas-box',
    authDomain: 'nas-box.firebaseapp.com',
    storageBucket: 'nas-box.appspot.com',
    measurementId: 'G-1GVN95ZPWW',
  );
}
